name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      # ADD THIS IF YOUR GRADLEW IS NOT AT THE ROOT
      # - name: Build with Gradle
      #   run: ./gradlew assembleDebug
      #   working-directory: ./your-folder-name-here 

      # IF GRADLEW IS AT THE ROOT, ENSURE IT IS EXECUTABLE:
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Build with Gradle
        run: ./gradlew assembleDebug
